### ISSUE TITLE
Объединяйте в одну строку, не нужно разбивать на две

### ISSUE THREAD

**Issue by coursar** [MoiseevaAlena/Task-1-fuel-consumption#3]
https://github.com/MoiseevaAlena/Task-1-fuel-consumption/blob/a8b9dca08846dd61415f312cc3a2eea37417a61d/src/Main.java#L14-L15

**Comment by coursar** [comment]
Не надо на меня перезназначать, просто закрывайте.

**Comment by MoiseevaAlena** [comment]
@coursar хорошо
